<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

1. Compute the scaler product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number. 

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [1]:
import numpy as np


In [4]:
a = [-12, 16]
b = [12, 9]

In [7]:
# Dot product of a & b. Insert answer here

np.matmul(a, b)


0

2. Compute the cross product of two vectors

        
Hint: [Cross Product](https://www.mathsisfun.com/algebra/vectors-cross-product.html)

In [9]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])

In [10]:
# Cross product of a & b. Insert answer here

np.cross(x, y)

array([[-3,  6, -3],
       [ 3, -6,  3]])

3. Compute the Hademard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [12]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [13]:
# Hademard product of a & b. Insert answer here

a * b

array([[ 5, 12],
       [21, 32]])

4. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [52]:
# Program to add two matrices using nested loop

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]


# initialise result

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

In [53]:
# hint : # iterate through rows & iterate through columns

# iterate through rows
for i in range(len(X)): # -- creates a list for the index number 0 to no. of elements in X. hence, here is 0,1,2
    
   # iterate through columns
   for j in range(len(X[0])): # -- creates a list for the index number 0 to no. of elements in the first list in X. 
        # hence, here is 0,1,2 

       result[i][j] = X[i][j] + Y[i][j] 
        # here adds the elements by index for the 2 lists X and Y and fills it up in the result list. 
        #e.g. x[0][0] + y[0][0] = 12 + 5 = 17. hence, result[0][0] changes from 0 to 17. applies for all.
        #loops through all the 

for r in result: #prints each element in the result list
   print(r)


[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [22]:
#numpy method:

def sum_matrix(m1, m2):
    x1 = np.array(m1)
    y1 = np.array(m2)
    z1 = x1 + y1
    return z1

sum_matrix(X, Y)

array([[17, 15,  4],
       [10, 12,  9],
       [11, 13, 18]])

In [90]:
# Alternative - one line of code


In [57]:
#list comprehension form of the nested for loop above:

answer = [print(r) for r in [[X[i][j] + Y[i][j]  for j in range(len(X[0]))] for i in range(len(X))]]

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


5. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [86]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

In [31]:
#using nested for loops to solve

# iterating by row of X
for i in range(len(X)): # -- creates a list for the index number 0 to no. of elements in X. hence, here is 0,1,2
  
    # iterating by column by Y
    for j in range(len(Y[0])): # -- creates a list for the index number 0 to no. of elements in the first list in Y. 
        #hence, here is 0,1,2,3 
  
        # iterating by rows of Y
        for k in range(len(Y)): # -- pulls the number 0 to no. of elements in Y. hence, here is 0,1,2
            
            result[i][j] += X[i][k] * Y[k][j] 
            # here multiplies the elements by the assigned index for the 2 lists X and Y then continue to 
            # add them up for the number of times of k (which is 3 times) and fills it up in the result list.
           #e.g. X[0][0] * Y[0][0] + X[0][1] * Y[1][0] + X[0][2] * Y[2][0]= 12*5 + 7*6 + 3*4 = 114. 
           #hence, result[0][0] changes from 0 to 17. goes from [0][0] to [0][3] until [3][3].
  
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [63]:
12*5+7*6+3*4

114

[(5, 6, 4), (8, 7, 5), (1, 3, 9), (2, 0, 1)]

In [68]:
#using zip to solve

# result will be 3x4
result = [[sum(a * b for a, b in zip(X_row, Y_col)) # zip each list in X with each tuple in zip of Y into a new list of tuples.
                        for Y_col in zip(*Y)] # zip the Y list into a list of tuples. see below.
                                for X_row in X] # iterate each list in X
#
  
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [85]:
#zip Y list into a list of tuples
y = (zip(*Y))

y = list(y)

y


[(5, 6, 4), (8, 7, 5), (1, 3, 9), (2, 0, 1)]

In [88]:
#using numpy to solve
A = np.array(X)
B = np.array(Y)
print(A@B)

[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]


In [35]:
#using numpy to solve

result = np.dot(X,Y)
  
for r in result:
    print(r)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


6. Compute the determinant of an n x n matrix.

![](https://integratedmlai.com/wp-content/uploads/2018/12/Matrix_Det_2x2.png)



Hint: Use 
> np.linalg.det

Alt. Hint: [Find the Determinant of a Matrix with Pure Python without Numpy or Scipy](https://integratedmlai.com/find-the-determinant-of-a-matrix-with-pure-python-without-numpy-or-scipy/)

In [46]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]



In [48]:
#using numpy to calculate determinant

m_array = np.array(matrix)

det = np.linalg.det(m_array)

det

17.999999999999996

7. Compute the inverse of an n x n matrix.

For a 3×3 matrix

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation3.gif)

the matrix inverse is

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation4.gif)

Hint: Use 
> from numpy.linalg import inv

In [49]:
a = np.array([[1., 2.], [3., 4.]])

In [51]:
from numpy.linalg import inv

inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])



---



---



> > > > > > > > > © 2021 Institute of Data


---



---



