<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 3.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [4]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [2]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.19.2
Pandas:  1.1.3


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [21]:
# wrong:
bikes = pd.read_table('C:/Users/imran/OneDrive/Desktop/lesson notes/bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('C:/Users/imran/OneDrive/Desktop/lesson notes/bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('C:/Users/imran/OneDrive/Desktop/lesson notes/bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

?:
ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [7]:
#ANSWER:

bikes = pd.read_csv('C:/Users/imran/OneDrive/Desktop/lesson notes/bikeshare.csv')
bikes.head()


instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13  
4           1  0.24  0.2879  0.75        0.0       0           1    1

Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [8]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [9]:
df = pd.read_excel('C:/Users/imran/OneDrive/Desktop/lesson notes/Iris.xls', sheet_name = 'Data')
df

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0             1          0.2           1.4          3.5           5.1   
1             1          0.2           1.4          3.0           4.9   
2             1          0.2           1.3          3.2           4.7   
3             1          0.2           1.5          3.1           4.6   
4             1          0.2           1.4          3.6           5.0   
..          ...          ...           ...          ...           ...   
145           3          2.3           5.2          3.0           6.7   
146           3          1.9           5.0          2.5           6.3   
147           3          2.0           5.2          3.0           6.5   
148           3          2.3           5.4          3.4           6.2   
149           3          1.8           5.1          3.0           5.9   

    Species_name  
0         Setosa  
1         Setosa  
2         Setosa  
3         Setosa  
4         Setosa  
..           ...  
145    Verginica  
146    Verginica  
147    Verginica  
148    Verginica  
149    Verginica  

[150 rows x 6 columns]

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [28]:
#ANSWER


### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [5]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

#for this link there may not be any results if the website is refreshing its data

time  latitude  longitude  depth   mag magType  nst  \
0  2021-05-05T02:15:37.760Z   17.9585   -66.8353      7  2.56      md   16   

   gap    dmin   rms  ...                   updated  \
0  185  0.2092  0.23  ...  2021-05-05T02:33:31.773Z   

                             place        type horizontalError depthError  \
0  4 km SSW of Indios, Puerto Rico  earthquake            0.61       1.08   

   magError  magNst    status  locationSource magSource  
0      0.17       6  reviewed              pr        pr  

[1 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [7]:
url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'
df = pd.read_html(url)
df

[                             Bank Name               City State   Cert  \
 0                    Almena State Bank             Almena    KS  15426   
 1           First City Bank of Florida  Fort Walton Beach    FL  16748   
 2                 The First State Bank      Barboursville    WV  14361   
 3                   Ericson State Bank            Ericson    NE  18265   
 4     City National Bank of New Jersey             Newark    NJ  21111   
 ..                                 ...                ...   ...    ...   
 558                 Superior Bank, FSB           Hinsdale    IL  32646   
 559                Malta National Bank              Malta    OH   6629   
 560    First Alliance Bank & Trust Co.         Manchester    NH  34264   
 561  National State Bank of Metropolis         Metropolis    IL   3815   
 562                   Bank of Honolulu           Honolulu    HI  21029   
 
                    Acquiring Institution       Closing Date  
 0                            Equit

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [8]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [48]:
#ANSWER

len(bikes.columns) #no. of columns


17

In [50]:
len(bikes.values) #no. of rows

17379

In [11]:
bikes.count()

instant       17379
dteday        17379
season        17379
yr            17379
mnth          17379
hr            17379
holiday       17379
weekday       17379
workingday    17379
weathersit    17379
temp          17379
atemp         17379
hum           17379
windspeed     17379
casual        17379
registered    17379
cnt           17379
dtype: int64

What are the column names in `bikes`?

In [51]:
#ANSWER

bikes.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

What are the data types of these columns?

In [52]:
#ANSWER
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

What is the (row) index for this DataFrame?

In [53]:
#ANSWER

bikes.index


RangeIndex(start=0, stop=17379, step=1)

https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [54]:
#ANSWER
bikes['season']


0        1
1        1
2        1
3        1
4        1
        ..
17374    1
17375    1
17376    1
17377    1
17378    1
Name: season, Length: 17379, dtype: int64

In [55]:
bikes[['season']]

season
0           1
1           1
2           1
3           1
4           1
...       ...
17374       1
17375       1
17376       1
17377       1
17378       1

[17379 rows x 1 columns]

How would we use object notation to show the first 4 rows of `atemp`?

In [58]:
#ANSWER

bikes['atemp'][:4]

0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [12]:
bikes[[0]]
#E: bikes[0]
#E: bikes[0,0]
#E: bikes[[0,0]]

What is the correct way to access the 1st row of the DataFrame by its index?

In [62]:
#ANSWER

bikes.loc[0]

instant                1
dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     0
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.24
atemp             0.2879
hum                 0.81
windspeed              0
casual                 3
registered            13
cnt                   16
Name: 0, dtype: object

In [64]:
bikes.loc[[0]]

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16

In [67]:
bikes.iloc[0]

instant                1
dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     0
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.24
atemp             0.2879
hum                 0.81
windspeed              0
casual                 3
registered            13
cnt                   16
Name: 0, dtype: object

In [68]:
bikes.iloc[[0]]

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16

What is the correct way to access the 2nd column of the DataFrame by its index?

In [73]:
#ANSWER

bikes.iloc[:,1]


0        2011-01-01
1        2011-01-01
2        2011-01-01
3        2011-01-01
4        2011-01-01
            ...    
17374    2012-12-31
17375    2012-12-31
17376    2012-12-31
17377    2012-12-31
17378    2012-12-31
Name: dteday, Length: 17379, dtype: object

In [74]:
bikes.iloc[:,[1]]

dteday
0      2011-01-01
1      2011-01-01
2      2011-01-01
3      2011-01-01
4      2011-01-01
...           ...
17374  2012-12-31
17375  2012-12-31
17376  2012-12-31
17377  2012-12-31
17378  2012-12-31

[17379 rows x 1 columns]

## Handling Missing Values

What is the Pandas `isnull` function for? 

?
ANSWER:

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [76]:
bikes.isnull().head()

instant  dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
0    False   False   False  False  False  False    False    False       False   
1    False   False   False  False  False  False    False    False       False   
2    False   False   False  False  False  False    False    False       False   
3    False   False   False  False  False  False    False    False       False   
4    False   False   False  False  False  False    False    False       False   

   weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
0       False  False  False  False      False   False       False  False  
1       False  False  False  False      False   False       False  False  
2       False  False  False  False      False   False       False  False  
3       False  False  False  False      False   False       False  False  
4       False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in the 'windspeed' column of `bikes` altogether?

In [14]:
#ANSWER

w = bikes['windspeed']

w.isnull()


0        False
1        False
2        False
3        False
4        False
         ...  
17374    False
17375    False
17376    False
17377    False
17378    False
Name: windspeed, Length: 17379, dtype: bool

In [15]:
w.isnull().sum()

0

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [20]:
#ANSWER

w[w.isnull() == True]


Series([], Name: windspeed, dtype: float64)

What is the Numpy object `nan` used for? (Write a descriptive answer.)

?
ANSWER: Marking a data point as invalid.

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [ ]:
#ANSWER


Apply the Pandas `isna` function to the following data objects:

In [23]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [29]:
#ANSWER

print(x.isna())
print(y.isna())

AttributeError: 'float' object has no attribute 'isna'

In [31]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [32]:
#ANSWER
print(array.isna())

AttributeError: 'numpy.ndarray' object has no attribute 'isna'

How is the pandas I/O parameter `na_values` used?

? ANSWER: 

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [80]:
#ANSWER

s = bikes['season']

s.unique()


array([1, 2, 3, 4], dtype=int64)

In [83]:
s.value_counts()

3    4496
2    4409
1    4242
4    4232
Name: season, dtype: int64

### Ranges

Print the range (i.e. min & max values) of the `instant`, `dteday`, and `windspeed` columns: 

In [90]:
#ANSWER

d = bikes.describe()
d



instant        season            yr          mnth            hr  \
count  17379.0000  17379.000000  17379.000000  17379.000000  17379.000000   
mean    8690.0000      2.501640      0.502561      6.537775     11.546752   
std     5017.0295      1.106918      0.500008      3.438776      6.914405   
min        1.0000      1.000000      0.000000      1.000000      0.000000   
25%     4345.5000      2.000000      0.000000      4.000000      6.000000   
50%     8690.0000      3.000000      1.000000      7.000000     12.000000   
75%    13034.5000      3.000000      1.000000     10.000000     18.000000   
max    17379.0000      4.000000      1.000000     12.000000     23.000000   

            holiday       weekday    workingday    weathersit          temp  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000   
mean       0.028770      3.003683      0.682721      1.425283      0.496987   
std        0.167165      2.005771      0.465431      0.639357      0.192556   
min        0.000000      0.000000      0.000000      1.000000      0.020000   
25%        0.000000      1.000000      0.000000      1.000000      0.340000   
50%        0.000000      3.000000      1.000000      1.000000      0.500000   
75%        0.000000      5.000000      1.000000      2.000000      0.660000   
max        1.000000      6.000000      1.000000      4.000000      1.000000   

              atemp           hum     windspeed        casual    registered  \
count  17379.000000  17379.000000  17379.000000  17379.000000  17379.000000   
mean       0.475775      0.627229      0.190098     35.676218    153.786869   
std        0.171850      0.192930      0.122340     49.305030    151.357286   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.333300      0.480000      0.104500      4.000000     34.000000   
50%        0.484800      0.630000      0.194000     17.000000    115.000000   
75%        0.621200      0.780000      0.253700     48.000000    220.000000   
max        1.000000      1.000000      0.850700    367.000000    886.000000   

                cnt  
count  17379.000000  
mean     189.463088  
std      181.387599  
min        1.000000  
25%       40.000000  
50%      142.000000  
75%      281.000000  
max      977.000000

In [92]:
print(d['instant'])
print(d['windspeed'])

count    17379.0000
mean      8690.0000
std       5017.0295
min          1.0000
25%       4345.5000
50%       8690.0000
75%      13034.5000
max      17379.0000
Name: instant, dtype: float64
count    17379.000000
mean         0.190098
std          0.122340
min          0.000000
25%          0.104500
50%          0.194000
75%          0.253700
max          0.850700
Name: windspeed, dtype: float64


In [98]:
print(bikes['instant'].min())
print(bikes['instant'].max())

print(bikes['windspeed'].min())
print(bikes['windspeed'].max())

1
17379
0.0
0.8507


Compute and print the overall (dataframe) minimum and maximum of the numeric data columns:

In [110]:
bikes_min, bikes_max = (min(bikes.min()), max(bikes.max()))
bikes_min, bikes_max

TypeError: '<' not supported between instances of 'str' and 'int'

In [125]:
d = bikes.describe()

print(d.loc[['min']])
print(d.loc[['max']])



     instant  season   yr  mnth   hr  holiday  weekday  workingday  \
min      1.0     1.0  0.0   1.0  0.0      0.0      0.0         0.0   

     weathersit  temp  atemp  hum  windspeed  casual  registered  cnt  
min         1.0  0.02    0.0  0.0        0.0     0.0         0.0  1.0  
     instant  season   yr  mnth    hr  holiday  weekday  workingday  \
max  17379.0     4.0  1.0  12.0  23.0      1.0      6.0         1.0   

     weathersit  temp  atemp  hum  windspeed  casual  registered    cnt  
max         4.0   1.0    1.0  1.0     0.8507   367.0       886.0  977.0  


### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [102]:
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [103]:
#ANSWER
bikes['atemp'].quantile([.1, .25, .5, .75,.95])

0.10    0.2424
0.25    0.3333
0.50    0.4848
0.75    0.6212
0.95    0.7424
Name: atemp, dtype: float64

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [33]:
type(bikes['atemp'])

pandas.core.series.Series

In [34]:
bikes.sample(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
5136      5137  2011-08-06       3   0     8  22        0        6   
15582    15583  2012-10-16       4   1    10  11        0        2   
12996    12997  2012-06-30       3   1     6  17        0        6   
2693      2694  2011-04-27       2   0     4   3        0        3   
11606    11607  2012-05-03       2   1     5  19        0        4   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
5136            0           2  0.70  0.6667  0.84     0.3284      24   
15582           1           1  0.50  0.4848  0.45     0.4179      56   
12996           0           1  0.88  0.7727  0.32     0.1343     131   
2693            1           2  0.58  0.5455  0.88     0.2836       3   
11606           1           1  0.70  0.6515  0.61     0.1940      55   

       registered  cnt  
5136           96  120  
15582         172  228  
12996         231  362  
2693            4    7  
11606         467  522

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [35]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)         

What typre is `atemp_level`?

In [36]:
#ANSWER

type(atemp_level)


pandas.core.series.Series

Here is a random sample of `atemp_level`:

In [37]:
atemp_level.sample(5)          

2568     (0.25, 0.5]
17006    (0.25, 0.5]
4745     (0.75, 1.0]
5903     (0.5, 0.75]
4835     (0.75, 1.0]
Name: atemp, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [38]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

849      mild
9642     cool
10751    warm
5785     warm
4136     warm
Name: atemp, dtype: category
Categories (4, object): ['cool' < 'mild' < 'warm' < 'hot']

Add the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [39]:
#ANSWER
bikes['atemp_level'] = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
# add the new details as a new column in bikes

bikes.head()

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   
4        5  2011-01-01       1   0     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  \
0           1  0.24  0.2879  0.81        0.0       3          13   16   
1           1  0.22  0.2727  0.80        0.0       8          32   40   
2           1  0.22  0.2727  0.80        0.0       5          27   32   
3           1  0.24  0.2879  0.75        0.0       3          10   13   
4           1  0.24  0.2879  0.75        0.0       0           1    1   

  atemp_level  
0        mild  
1        mild  
2        mild  
3        mild  
4        mild

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [240]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

In [264]:
print(np.shape(a))
print(a)

(3,)
[0. 0. 0.]


In [245]:
list = [a, b, c, d, e]

In [263]:
def shape_and_content(x):
    for i, val in enumerate(x):
        print (i+1, "shape: ",np.shape(val), "contents: ",val )
        
shape_and_content(list)

1 shape:  (3,) contents:  [0. 0. 0.]
2 shape:  (1, 3) contents:  [[1. 1. 1.]]
3 shape:  (2, 3, 4) contents:  [[[7 2 8 9]
  [9 9 9 6]
  [3 7 6 9]]

 [[9 7 7 1]
  [6 8 7 5]
  [4 5 2 7]]]
4 shape:  (4,) contents:  [0 1 2 3]
5 shape:  (2, 4) contents:  [[1 2 3 4]
 [5 6 7 8]]


## Load Data

Load rock.csv and clean the dataset.

In [40]:
rock = pd.read_csv('C:/Users/imran/OneDrive/Desktop/lesson notes/rock.csv')
rock.head()

Song Clean ARTIST CLEAN Release Year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                COMBINED  First?  Year?  PlayCount  F*G  
0        Caught Up in You by .38 Special       1      1         82   82  
1            Fantasy Girl by .38 Special       1      0          3    0  
2         Hold On Loosely by .38 Special       1      1         85   85  
3  Rockin' Into the Night by .38 Special       1      1         18   18  
4              Art For Arts Sake by 10cc       1      1          1    1

## Check Column Names

Check column names and clean. e.g. consistent upper/lower case, remove punctuation etc.

In [41]:
rock.columns = rock.columns.str.lower() #change all to lowercase
rock.columns = rock.columns.map(lambda x : x.replace("-", "_").replace(" ", "_")) #fill spaces with underscore
rock.columns = rock.columns.map(lambda x : x.replace("?", "").replace("?", "")) #remove '?'

rock.head()

song_clean artist_clean release_year  \
0        Caught Up in You  .38 Special         1982   
1            Fantasy Girl  .38 Special          NaN   
2         Hold On Loosely  .38 Special         1981   
3  Rockin' Into the Night  .38 Special         1980   
4       Art For Arts Sake         10cc         1975   

                                combined  first  year  playcount  f*g  
0        Caught Up in You by .38 Special      1     1         82   82  
1            Fantasy Girl by .38 Special      1     0          3    0  
2         Hold On Loosely by .38 Special      1     1         85   85  
3  Rockin' Into the Night by .38 Special      1     1         18   18  
4              Art For Arts Sake by 10cc      1     1          1    1

## Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [42]:
rock['release_year'].isnull() #check for null values

0       False
1        True
2       False
3       False
4       False
        ...  
2225     True
2226    False
2227    False
2228    False
2229    False
Name: release_year, Length: 2230, dtype: bool

In [43]:
rock['release_year'].fillna(0, inplace = True) #change null values to 0

In [44]:
rock['release_year'][1504] #remove this

'SONGFACTS.COM'

In [45]:
rock.replace(to_replace=rock['release_year'][1504], value=0, inplace=True) #replace the recording error

In [46]:
rock['release_year'][1504]

0

## Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [47]:
rock.dtypes #identify types. noted that the release_year is an object when it should be an integer

song_clean      object
artist_clean    object
release_year    object
combined        object
first            int64
year             int64
playcount        int64
f*g              int64
dtype: object

In [48]:
rock["release_year"] = pd.to_numeric(rock["release_year"]) #change column datatype from object to integer

In [49]:
rock.dtypes #checked again. cleaned.

song_clean      object
artist_clean    object
release_year     int64
combined        object
first            int64
year             int64
playcount        int64
f*g              int64
dtype: object

## Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [50]:
rock.describe()

release_year   first         year    playcount          f*g
count   2230.000000  2230.0  2230.000000  2230.000000  2230.000000
mean    1465.331390     1.0     0.741256    16.872646    15.048430
std      867.196161     0.0     0.438043    25.302972    25.288366
min        0.000000     1.0     0.000000     0.000000     0.000000
25%        0.000000     1.0     0.000000     1.000000     0.000000
50%     1973.000000     1.0     1.000000     4.000000     3.000000
75%     1981.000000     1.0     1.000000    21.000000    18.000000
max     2014.000000     1.0     1.000000   142.000000   142.000000

## Write Some Functions

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not (true/false) if the release date is < 1970

In [51]:
def pre_1970_check(row_num):
    d1 = pd.DataFrame([])
    list1 = []
    d1['Song'] = rock['song_clean']
    d1['artist'] = rock['artist_clean']
    for num in rock['release_year']:
        if num == 0:
            list1.append('Unknown')
        elif num < 1970:
            list1.append('True')
        else:
            list1.append('False')
    d1['Release date before 1970?'] = list1
    return d1.iloc[[row_num]]


pre_1970_check(0)


Song       artist Release date before 1970?
0  Caught Up in You  .38 Special                     False

## Write a function that converts cells in a DataFrame column to float and if error, otherwise replaces them with np.nan

In [ ]:
 Need to convert strings to floats in Pandas DataFrame?

Depending on the scenario, you may use either of the following two approaches in order to convert strings to floats in Pandas DataFrame:

(1) astype(float)

df['DataFrame Column'] = df['DataFrame Column'].astype(float)

(2) to_numeric

df['DataFrame Column'] = pd.to_numeric(df['DataFrame Column'],errors='coerce')

df['DataFrame Column'] = df['DataFrame Column'].astype(float)


In [ ]:
def float_or_error

## Apply these functions to your dataset

## Describe the new float-only DataFrame.

>




---



---



> > > > > > > > > © 2021 Institute of Data


---



---



